### ISSUE TITLE
SIGSEGV after "edit" menu was accessed.

### ISSUE THREAD

**Issue by 6r1d** [emer/emergent#75]
Hello. I was trying to figure out the installation process, built `ra25` example and it works, besides one thing.
"Edit" menu click leads to the program freezing, and then closing shows this error in a terminal.

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x968 pc=0x7f6274142609]

runtime stack:
runtime.throw({0x169468f, 0x0})
	/usr/lib/go/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
	/usr/lib/go/src/runtime/signal_unix.go:719 +0x396

goroutine 25 [syscall]:
runtime.cgocall(0x139fcd0, 0xc000675988)
	/usr/lib/go/src/runtime/cgocall.go:156 +0x5c fp=0xc000675960 sp=0xc000675928 pc=0x42a25c
github.com/go-gl/glfw/v3.3/glfw._Cfunc_glfwGetClipboardString(0x0)
	_cgo_gotypes.go:792 +0x4d fp=0xc000675988 sp=0xc000675960 pc=0x134b24d
github.com/go-gl/glfw/v3.3/glfw.GetClipboardString()
	/home/grid/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210410170116-ea3d685f79fb/glfw.go:101 +0x25 fp=0xc0006759b8 sp=0xc000675988 pc=0x1350785
github.com/goki/gi/oswin/driver/glos.(*clipImpl).IsEmpty(0x150d4c0)
	/home/grid/go/pkg/mod/github.com/goki/gi@v1.2.11/oswin/driver/glos/glos_x11.go:78 +0x17 fp=0xc0006759c8 sp=0xc0006759b8 pc=0x136a137
github.com/goki/gi/gi.(*Menu).AddCopyCutPaste.func3(0xc001a8b980)
	/home/grid/go/pkg/mod/github.com/goki/gi@v1.2.11/gi/menus.go:241 +0x4f fp=0xc000675a08 sp=0xc0006759c8 pc=0xa5bfcf
github.com/goki/gi/gi.(*Action).UpdateActions(0xc001a8b980)
	/home/grid/go/pkg/mod/github.com/goki/gi@v1.2.11/gi/action.go:335 +0x2f fp=0xc000675a20 sp=0xc000675a08 pc=0xa2f88f
github.com/goki/gi/gi.(*Menu).UpdateActions(0x0)
	/home/grid/go/pkg/mod/github.com/goki/gi@v1.2.11/gi/menus.go:196 +0xb1 fp=0xc000675a78 sp=0xc000675a20 pc=0xa5bbb1
github.com/goki/gi/gi.PopupMenu({0xc000748f40, 0x3, 0x4}, 0x7a, 0x29, 0x0, {0x16141b6, 0x4})
	/home/grid/go/pkg/mod/github.com/goki/gi@v1.2.11/gi/menus.go:359 +0x9a fp=0xc000675b68 sp=0xc000675a78 pc=0xa5c87a
github.com/goki/gi/gi.(*ButtonBase).OpenMenu(0xc001a7c600)
	/home/grid/go/pkg/mod/github.com/goki/gi@v1.2.11/gi/buttons.go:379 +0x1fa fp=0xc000675bd8 sp=0xc000675b68 pc=0xa36f5a
github.com/goki/gi/gi.(*Action).ButtonRelease(0xc001a7c600)
	/home/grid/go/pkg/mod/github.com/goki/gi@v1.2.11/gi/action.go:225 +0x126 fp=0xc000675c28 sp=0xc000675bd8 pc=0xa2e846
github.com/goki/gi/gi.(*ButtonBase).MouseEvent.func1({0x190b7e8, 0xc001a7c600}, {0xc000675d01, 0xc000675c90}, 0x84f32d, {0x154dd20, 0xc002a07600})
	/home/grid/go/pkg/mod/github.com/goki/gi@v1.2.11/gi/buttons.go:455 +0xa8 fp=0xc000675c58 sp=0xc000675c28 pc=0xa9d468
github.com/goki/gi/gi.(*WinEventRecv).Call(0xc002a07600, {0x1911458, 0xc0008f4000}, 0xc000675db0, {0x154dd20, 0xc002a07600})
	/home/grid/go/pkg/mod/github.com/goki/gi@v1.2.11/gi/events.go:116 +0x139 fp=0xc000675cc8 sp=0xc000675c58 pc=0xa42a59
github.com/goki/gi/gi.(*EventMgr).SendEventSignal(0xc0008f4188, {0x18d6850, 0xc002a07600}, 0x1)
	/home/grid/go/pkg/mod/github.com/goki/gi@v1.2.11/gi/events.go:225 +0x61c fp=0xc000675dc0 sp=0xc000675cc8 pc=0xa4379c
github.com/goki/gi/gi.(*Window).ProcessEvent(0xc0008f4000, {0x18d6850, 0xc002a07600})
	/home/grid/go/pkg/mod/github.com/goki/gi@v1.2.11/gi/window.go:1576 +0x605 fp=0xc000675ee0 sp=0xc000675dc0 pc=0xa95065
github.com/goki/gi/gi.(*Window).EventLoop(0xc0008f4000)
	/home/grid/go/pkg/mod/github.com/goki/gi@v1.2.11/gi/window.go:1498 +0x33 fp=0xc000675f50 sp=0xc000675ee0 pc=0xa948f3
github.com/goki/gi/gi.(*Window).StartEventLoop(0xc0008f4000)
	/home/grid/go/pkg/mod/github.com/goki/gi@v1.2.11/gi/window.go:868 +0x50 fp=0xc000675f88 sp=0xc000675f50 pc=0xa902b0
main.guirun()
	/home/grid/.software/emergent_requirements/leabra/examples/ra25/ra25.go:58 +0x36 fp=0xc000675fa0 sp=0xc000675f88 pc=0x13744d6
main.main.func1()
	/home/grid/.software/emergent_requirements/leabra/examples/ra25/ra25.go:50 +0x17 fp=0xc000675fb0 sp=0xc000675fa0 pc=0x137eaf7
github.com/goki/gi/gimain.Main.func1({0x0, 0x0})
	/home/grid/go/pkg/mod/github.com/goki/gi@v1.2.11/gimain/gimain.go:31 +0x1b fp=0xc000675fc0 sp=0xc000675fb0 pc=0x13742db
github.com/goki/gi/oswin/driver/glos.Main.func1()
	/home/grid/go/pkg/mod/github.com/goki/gi@v1.2.11/oswin/driver/glos/app.go:88 +0x2e fp=0xc000675fe0 sp=0xc000675fc0 pc=0x13726ee
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000675fe8 sp=0xc000675fe0 pc=0x48c361
created by github.com/goki/gi/oswin/driver/glos.Main
	/home/grid/go/pkg/mod/github.com/goki/gi@v1.2.11/oswin/driver/glos/app.go:87 +0x86

goroutine 1 [panicwait, locked to thread]:
runtime.gopark(0xc00010e000, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/runtime/proc.go:366 +0xd6
runtime.main()
	/usr/lib/go/src/runtime/proc.go:274 +0x270
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1581 +0x1

goroutine 24 [chan receive]:
github.com/emer/leabra/leabra.(*NetworkStru).ThrWorker(0xc0002602d0, 0x0)
	/home/grid/.software/emergent_requirements/leabra/leabra/networkstru.go:638 +0xa5
created by github.com/emer/leabra/leabra.(*NetworkStru).StartThreads
	/home/grid/.software/emergent_requirements/leabra/leabra/networkstru.go:622 +0x105

goroutine 26 [chan send]:
github.com/goki/gi/oswin/driver/glos.(*appImpl).RunOnMain(0x25329a0, 0xc00073b5e0)
	/home/grid/go/pkg/mod/github.com/goki/gi@v1.2.11/oswin/driver/glos/app.go:106 +0x6c
github.com/goki/gi/oswin/driver/glos.(*windowImpl).Close(0xc0000cf500)
	/home/grid/go/pkg/mod/github.com/goki/gi@v1.2.11/oswin/driver/glos/window.go:542 +0xe9
github.com/goki/gi/oswin/driver/glos.(*windowImpl).CloseReq(0x0)
	/home/grid/go/pkg/mod/github.com/goki/gi@v1.2.11/oswin/driver/glos/window.go:524 +0x55
created by github.com/goki/gi/oswin/driver/glos.(*windowImpl).closeReq
	/home/grid/go/pkg/mod/github.com/goki/gi@v1.2.11/oswin/driver/glos/window.go:704 +0x5b

[1]  + 19506 exit 2     ./ra25
```

Context:

* Artix Linux, kernel v. 5.14.8
* Wayland 1.19.0-1
* Go 1.17.1 linux/amd64
* AMD Ryzen 5 4500U with Radeon Graphics

**Comment by rcoreilly** [comment]
Thanks -- seems like a bug in glfw -- are you running Wayland probably?  I think it may have some issues there.  I had a similar issue before like that on Wayland.
